include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    avoid_relative_lib_imports: true
    avoid_dynamic_calls: true
    always_declare_return_types: true
    eol_at_end_of_file: true
    enable_null_safety: true
